// Generated: 8. sınıf LGS kazanım kodu -> [ders, konu, MEB ünite/öğrenme alanı].
// Kaynak: MEB LGS kazanım kataloğu (konu/ünite adları) ve MEB 8. sınıf kazanım kitapçığı (Cilt 1) ile doğrulandı;
// katalogda olmayan 4 kademeli üst kodlar, alt kodların aynı konuda birleştiği durumda eklenmiştir.
export const LGS8_KAZANIM_TOPICS = {
  "D.8.1.1.": ["din", "Kader ve Kaza İnancı", "Kader İnancı"],
  "D.8.1.2.": ["din", "İnsanın İradesi ve Kader", "Kader İnancı"],
  "D.8.1.3.": ["din", "Kaderle İlgili Kavramlar", "Kader İnancı"],
  "D.8.1.4.": ["din", "Kaderle İlgili Kavramlar", "Kader İnancı"],
  "D.8.1.5.": ["din", "Bir Peygamber Tanıyorum: Hz. Musa (a.s.)", "Kader İnancı"],
  "D.8.1.6.": ["din", "Bir Ayet Tanıyorum: Ayet el-Kürsi ve Anlamı", "Kader İnancı"],
  "D.8.2.1.": ["din", "İslam’ın Paylaşma ve Yardımlaşmaya Verdiği Önem", "Zekât ve Sadaka"],
  "D.8.2.2.": ["din", "Zekât ve Sadaka İbadeti", "Zekât ve Sadaka"],
  "D.8.2.3.": ["din", "Zekât ve Sadakanın Bireysel ve Toplumsal Faydaları", "Zekât ve Sadaka"],
  "D.8.2.4.": ["din", "Bir Peygamber Tanıyorum: Hz. Şuayb (a.s.)", "Zekât ve Sadaka"],
  "D.8.2.5.": ["din", "Bir Sure Tanıyorum: Maûn Suresi ve Anlamı", "Zekât ve Sadaka"],
  "D.8.3.1.": ["din", "Din, Birey ve Toplum", "Din ve Hayat"],
  "D.8.3.2.": ["din", "Dinin Temel Gayesi", "Din ve Hayat"],
  "D.8.3.3.": ["din", "Bir Peygamber Tanıyorum: Hz. Yusuf (a.s.)", "Din ve Hayat"],
  "D.8.3.4.": ["din", "Bir Sure Tanıyorum: Asr Suresi ve Anlamı", "Din ve Hayat"],
  "D.8.4.1.": ["din", "Hz. Muhammed'in (s.a.v.) Doğruluğu ve Güvenilir Kişiliği", "Hz. Muhammed'in Örnekliği"],
  "D.8.4.2.": ["din", "Hz. Muhammed'in (s.a.v.) Merhametli ve Affedici Oluşu", "Hz. Muhammed'in Örnekliği"],
  "D.8.4.3.": ["din", "Hz. Muhammed'in (s.a.v.) İstişareye Önem Vermesi", "Hz. Muhammed'in Örnekliği"],
  "D.8.4.4.": ["din", "Hz. Muhammed'in (s.a.v.) Davasındaki Cesaret ve Kararlılığı", "Hz. Muhammed'in Örnekliği"],
  "D.8.4.5.": ["din", "Hz. Muhammed'in (s.a.v.) Hakkı Gözetmedeki Hassasiyeti", "Hz. Muhammed'in Örnekliği"],
  "D.8.4.6.": ["din", "Hz. Muhammed'in (s.a.v.) İnsanlara Değer Vermesi", "Hz. Muhammed'in Örnekliği"],
  "D.8.4.7.": ["din", "Hz. Muhammed'in (s.a.v.) İnsanlara Değer Vermesi", "Hz. Muhammed'in Örnekliği"],
  "D.8.4.8.": ["din", "Hz. Muhammed'in (s.a.v.) İnsanlara Değer Vermesi", "Hz. Muhammed'in Örnekliği"],
  "D.8.4.9.": ["din", "Bir Sure Tanıyorum: Kureyş Suresi ve Anlamı", "Hz. Muhammed'in Örnekliği"],
  "D.8.5.1.": ["din", "İslam Dininin Temel Kaynakları", "Kur’an-ı Kerim ve Özellikleri"],
  "D.8.5.2.": ["din", "Kur’an-ı Kerim’in Ana Konuları", "Kur’an-ı Kerim ve Özellikleri"],
  "D.8.5.3.": ["din", "Kur’an-ı Kerim’in Temel Özellikleri", "Kur’an-ı Kerim ve Özellikleri"],
  "D.8.5.4.": ["din", "Bir Peygamber Tanıyorum: Hz. Nuh (a.s.)", "Kur’an-ı Kerim ve Özellikleri"],
  "E.8.1.1.": ["ingilizce", "Friendship", "Friendship"],
  "E.8.1.2.": ["ingilizce", "Friendship", "Friendship"],
  "E.8.2.1.": ["ingilizce", "Teen Life", "Teen Life"],
  "E.8.2.2.": ["ingilizce", "Teen Life", "Teen Life"],
  "E.8.2.3.": ["ingilizce", "Teen Life", "Teen Life"],
  "E.8.3.1.": ["ingilizce", "In The Kitchen", "In The Kitchen"],
  "E.8.3.2.": ["ingilizce", "In The Kitchen", "In The Kitchen"],
  "E.8.3.3.": ["ingilizce", "In The Kitchen", "In The Kitchen"],
  "E.8.4.1.": ["ingilizce", "On The Phone", "On The Phone"],
  "E.8.4.2.": ["ingilizce", "On The Phone", "On The Phone"],
  "E.8.5.1.": ["ingilizce", "The Internet", "The Internet"],
  "E.8.6.1.": ["ingilizce", "Adventures", "Adventures"],
  "E.8.6.2.": ["ingilizce", "Adventures", "Adventures"],
  "E.8.7.1.": ["ingilizce", "Tourism", "Tourism"],
  "E.8.7.2.": ["ingilizce", "Tourism", "Tourism"],
  "E.8.7.3.": ["ingilizce", "Tourism", "Tourism"],
  "E.8.7.4.": ["ingilizce", "Tourism", "Tourism"],
  "E.8.7.5.": ["ingilizce", "Tourism", "Tourism"],
  "E.8.8.1.": ["ingilizce", "Chores", "Chores"],
  "E.8.8.2.": ["ingilizce", "Chores", "Chores"],
  "E.8.8.3.": ["ingilizce", "Chores", "Chores"],
  "E.8.9.1.": ["ingilizce", "Science", "Science"],
  "E.8.9.2.": ["ingilizce", "Science", "Science"],
  "E.8.10.1.": ["ingilizce", "Natural Forces", "Natural Forces"],
  "F.8.1.1.1.": ["fen", "Mevsimlerin Oluşumu", "Mevsimler ve İklim"],
  "F.8.1.2.1.": ["fen", "İklim ve Hava Hareketleri", "Mevsimler ve İklim"],
  "F.8.1.2.2.": ["fen", "İklim ve Hava Hareketleri", "Mevsimler ve İklim"],
  "F.8.2.1.1.": ["fen", "DNA ve Genetik Kod", "DNA ve Genetik Kod"],
  "F.8.2.1.2.": ["fen", "DNA ve Genetik Kod", "DNA ve Genetik Kod"],
  "F.8.2.1.3.": ["fen", "DNA ve Genetik Kod", "DNA ve Genetik Kod"],
  "F.8.2.2.1.": ["fen", "Kalıtım", "DNA ve Genetik Kod"],
  "F.8.2.2.2.": ["fen", "Kalıtım", "DNA ve Genetik Kod"],
  "F.8.2.2.3.": ["fen", "Kalıtım", "DNA ve Genetik Kod"],
  "F.8.2.3.1.": ["fen", "Mutasyon ve Modifikasyon", "DNA ve Genetik Kod"],
  "F.8.2.3.2.": ["fen", "Mutasyon ve Modifikasyon", "DNA ve Genetik Kod"],
  "F.8.2.3.3.": ["fen", "Mutasyon ve Modifikasyon", "DNA ve Genetik Kod"],
  "F.8.2.4.1.": ["fen", "Adaptasyon (Çevreye Uyum)", "DNA ve Genetik Kod"],
  "F.8.2.5.1.": ["fen", "Biyoteknoloji", "DNA ve Genetik Kod"],
  "F.8.2.5.2.": ["fen", "Biyoteknoloji", "DNA ve Genetik Kod"],
  "F.8.2.5.3.": ["fen", "Biyoteknoloji", "DNA ve Genetik Kod"],
  "F.8.3.1.1.": ["fen", "Basınç", "Basınç"],
  "F.8.3.1.2.": ["fen", "Basınç", "Basınç"],
  "F.8.3.1.3.": ["fen", "Basınç", "Basınç"],
  "F.8.4.1.1.": ["fen", "Periyodik Sistem", "Madde ve Endüstri"],
  "F.8.4.1.2.": ["fen", "Periyodik Sistem", "Madde ve Endüstri"],
  "F.8.4.2.1.": ["fen", "Fiziksel ve Kimyasal Değişimler", "Madde ve Endüstri"],
  "F.8.4.3.1.": ["fen", "Kimyasal Tepkimeler", "Madde ve Endüstri"],
  "F.8.4.4.1.": ["fen", "Asitler ve Bazlar", "Madde ve Endüstri"],
  "F.8.4.4.2.": ["fen", "Asitler ve Bazlar", "Madde ve Endüstri"],
  "F.8.4.4.3.": ["fen", "Asitler ve Bazlar", "Madde ve Endüstri"],
  "F.8.4.4.4.": ["fen", "Asitler ve Bazlar", "Madde ve Endüstri"],
  "F.8.4.4.5.": ["fen", "Asitler ve Bazlar", "Madde ve Endüstri"],
  "F.8.4.4.6.": ["fen", "Asitler ve Bazlar", "Madde ve Endüstri"],
  "F.8.4.4.7.": ["fen", "Asitler ve Bazlar", "Madde ve Endüstri"],
  "F.8.4.5.1.": ["fen", "Maddenin Isı ile Etkileşimi", "Madde ve Endüstri"],
  "F.8.4.5.2.": ["fen", "Maddenin Isı ile Etkileşimi", "Madde ve Endüstri"],
  "F.8.4.5.3.": ["fen", "Maddenin Isı ile Etkileşimi", "Madde ve Endüstri"],
  "F.8.4.5.4.": ["fen", "Maddenin Isı ile Etkileşimi", "Madde ve Endüstri"],
  "F.8.4.6.1.": ["fen", "Türkiye'de Kimya Endüstrisi", "Madde ve Endüstri"],
  "F.8.4.6.2.": ["fen", "Türkiye'de Kimya Endüstrisi", "Madde ve Endüstri"],
  "F.8.5.1.1.": ["fen", "Basit Makineler", "Basit Makineler"],
  "F.8.5.1.2.": ["fen", "Basit Makineler", "Basit Makineler"],
  "F.8.6.1.1.": ["fen", "Besin Zinciri ve Enerji Akışı", "Enerji Dönüşümleri ve Çevre Bilimi"],
  "F.8.6.2.1.": ["fen", "Enerji Dönüşümleri", "Enerji Dönüşümleri ve Çevre Bilimi"],
  "F.8.6.2.2.": ["fen", "Enerji Dönüşümleri", "Enerji Dönüşümleri ve Çevre Bilimi"],
  "F.8.6.2.3.": ["fen", "Enerji Dönüşümleri", "Enerji Dönüşümleri ve Çevre Bilimi"],
  "F.8.6.3.1.": ["fen", "Madde Döngüleri ve Çevre Sorunları", "Enerji Dönüşümleri ve Çevre Bilimi"],
  "F.8.6.3.2.": ["fen", "Madde Döngüleri ve Çevre Sorunları", "Enerji Dönüşümleri ve Çevre Bilimi"],
  "F.8.6.3.3.": ["fen", "Madde Döngüleri ve Çevre Sorunları", "Enerji Dönüşümleri ve Çevre Bilimi"],
  "F.8.6.4.1.": ["fen", "Sürdürülebilir Kalkınma", "Enerji Dönüşümleri ve Çevre Bilimi"],
  "F.8.6.4.2.": ["fen", "Sürdürülebilir Kalkınma", "Enerji Dönüşümleri ve Çevre Bilimi"],
  "F.8.6.4.3.": ["fen", "Sürdürülebilir Kalkınma", "Enerji Dönüşümleri ve Çevre Bilimi"],
  "F.8.6.4.4.": ["fen", "Sürdürülebilir Kalkınma", "Enerji Dönüşümleri ve Çevre Bilimi"],
  "F.8.6.4.5.": ["fen", "Sürdürülebilir Kalkınma", "Enerji Dönüşümleri ve Çevre Bilimi"],
  "F.8.7.1.1.": ["fen", "Elektrik Yükleri ve Elektriklenme", "Elektrik Yükleri ve Elektrik Enerjisi"],
  "F.8.7.1.2.": ["fen", "Elektrik Yükleri ve Elektriklenme", "Elektrik Yükleri ve Elektrik Enerjisi"],
  "F.8.7.1.3.": ["fen", "Elektrik Yükleri ve Elektriklenme", "Elektrik Yükleri ve Elektrik Enerjisi"],
  "F.8.7.2.1.": ["fen", "Elektrik Yüklü Cisimler", "Elektrik Yükleri ve Elektrik Enerjisi"],
  "F.8.7.2.2.": ["fen", "Elektrik Yüklü Cisimler", "Elektrik Yükleri ve Elektrik Enerjisi"],
  "F.8.7.3.1.": ["fen", "Elektrik Enerjisinin Dönüşümü", "Elektrik Yükleri ve Elektrik Enerjisi"],
  "F.8.7.3.2.": ["fen", "Elektrik Enerjisinin Dönüşümü", "Elektrik Yükleri ve Elektrik Enerjisi"],
  "F.8.7.3.3.": ["fen", "Elektrik Enerjisinin Dönüşümü", "Elektrik Yükleri ve Elektrik Enerjisi"],
  "F.8.7.3.4.": ["fen", "Elektrik Enerjisinin Dönüşümü", "Elektrik Yükleri ve Elektrik Enerjisi"],
  "F.8.7.3.5.": ["fen", "Elektrik Enerjisinin Dönüşümü", "Elektrik Yükleri ve Elektrik Enerjisi"],
  "F.8.7.3.6.": ["fen", "Elektrik Enerjisinin Dönüşümü", "Elektrik Yükleri ve Elektrik Enerjisi"],
  "İTA.8.1.1.": ["inkilap", "Uyanan Avrupa ve Sarsılan Osmanlı", "Bir Kahraman Doğuyor"],
  "İTA.8.1.2.": ["inkilap", "Mavi Gözlü Çocuk: Mustafa", "Bir Kahraman Doğuyor"],
  "İTA.8.1.3.": ["inkilap", "Buhranlar Büyük Kahramanlar Doğurur", "Bir Kahraman Doğuyor"],
  "İTA.8.1.4.": ["inkilap", "Adım Adım Liderliğe", "Bir Kahraman Doğuyor"],
  "İTA.8.2.1.": ["inkilap", "I. Dünya Savaşı’na Yol Açan Gelişmeler", "Millî Uyanış: Bağımsızlık Yolunda Atılan Adımlar"],
  "İTA.8.2.2.": ["inkilap", "Osmanlı Devleti’nin Son Savaşı: I. Dünya Savaşı", "Millî Uyanış: Bağımsızlık Yolunda Atılan Adımlar"],
  "İTA.8.2.3.": ["inkilap", "İşgal Yıllarında Anadolu", "Millî Uyanış: Bağımsızlık Yolunda Atılan Adımlar"],
  "İTA.8.2.4.": ["inkilap", "Cemiyetler ve Kuvâ-yi Millîye", "Millî Uyanış: Bağımsızlık Yolunda Atılan Adımlar"],
  "İTA.8.2.5.": ["inkilap", "İstiklal Yolculuğu", "Millî Uyanış: Bağımsızlık Yolunda Atılan Adımlar"],
  "İTA.8.2.6.": ["inkilap", "Büyük Millet Meclisine Karşı Çıkarılan Ayaklanmalar", "Millî Uyanış: Bağımsızlık Yolunda Atılan Adımlar"],
  "İTA.8.2.7.": ["inkilap", "Büyük Millet Meclisine Karşı Çıkarılan Ayaklanmalar", "Millî Uyanış: Bağımsızlık Yolunda Atılan Adımlar"],
  "İTA.8.2.8.": ["inkilap", "Geçersiz Bir Antlaşma: Sevr Antlaşması", "Millî Uyanış: Bağımsızlık Yolunda Atılan Adımlar"],
  "İTA.8.3.1.": ["inkilap", "Doğu ve Güney Cepheleri", "Millî Bir Destan: Ya İstiklal Ya Ölüm!"],
  "İTA.8.3.2.": ["inkilap", "Batı Cephesi", "Millî Bir Destan: Ya İstiklal Ya Ölüm!"],
  "İTA.8.3.3.": ["inkilap", "Maarif Kongresi", "Millî Bir Destan: Ya İstiklal Ya Ölüm!"],
  "İTA.8.3.4.": ["inkilap", "Millî Mücadele, Millî Seferberlik: Tekalif-i Millîye", "Millî Bir Destan: Ya İstiklal Ya Ölüm!"],
  "İTA.8.3.5.": ["inkilap", "Direnişten Dirilişe: Sakarya'dan Büyük Taarruz’a", "Millî Bir Destan: Ya İstiklal Ya Ölüm!"],
  "İTA.8.3.6.": ["inkilap", "Türkiye'nin Tapu Senedi: Lozan Antlaşması", "Millî Bir Destan: Ya İstiklal Ya Ölüm!"],
  "İTA.8.3.7.": ["inkilap", "Sanat ve Edebiyat Eserlerinde Millî Mücadele", "Millî Bir Destan: Ya İstiklal Ya Ölüm!"],
  "İTA.8.4.1.": ["inkilap", "Atatürk İlkeleri", "Atatürkçülük ve Çağdaşlaşan Türkiye"],
  "İTA.8.4.2.": ["inkilap", "Siyasi Alandaki Gelişmeler", "Atatürkçülük ve Çağdaşlaşan Türkiye"],
  "İTA.8.4.3.": ["inkilap", "Hukuk Alanındaki Gelişmeler", "Atatürkçülük ve Çağdaşlaşan Türkiye"],
  "İTA.8.4.4.": ["inkilap", "Eğitim ve Kültür Alanındaki Gelişmeler", "Atatürkçülük ve Çağdaşlaşan Türkiye"],
  "İTA.8.4.5.": ["inkilap", "Toplumsal Alandaki Gelişmeler", "Atatürkçülük ve Çağdaşlaşan Türkiye"],
  "İTA.8.4.6.": ["inkilap", "Ekonomi Alanındaki Gelişmeler", "Atatürkçülük ve Çağdaşlaşan Türkiye"],
  "İTA.8.4.7.": ["inkilap", "Sağlık Alanındaki Gelişmeler", "Atatürkçülük ve Çağdaşlaşan Türkiye"],
  "İTA.8.4.8.": ["inkilap", "İlelebet Cumhuriyet", "Atatürkçülük ve Çağdaşlaşan Türkiye"],
  "İTA.8.4.9.": ["inkilap", "Atatürk İlke ve İnkılaplarının Temel Esasları", "Atatürkçülük ve Çağdaşlaşan Türkiye"],
  "İTA.8.5.1.": ["inkilap", "Demokratikleşme Yolunda Atılan Adımlar", "Demokratikleşme Çabaları"],
  "İTA.8.5.2.": ["inkilap", "Mustafa Kemal'e Suikast Girişimi", "Demokratikleşme Çabaları"],
  "İTA.8.5.3.": ["inkilap", "Türkiye Cumhuriyeti’ne Yönelik Tehditler", "Demokratikleşme Çabaları"],
  "İTA.8.6.1.": ["inkilap", "Türk Dış Politikasının Temel İlkeleri", "Atatürk Dönemi Türk Dış Politikası"],
  "İTA.8.6.2.": ["inkilap", "Dış Politikada Yaşanan Gelişmeler", "Atatürk Dönemi Türk Dış Politikası"],
  "İTA.8.6.3.": ["inkilap", "Misak-ı Millî’nin Son Zaferi: Hatay", "Atatürk Dönemi Türk Dış Politikası"],
  "İTA.8.7.1.": ["inkilap", "Atatürk’ün Vefatı ve Yankıları", "Atatürk’ün Ölümü ve Sonrası"],
  "İTA.8.7.2.": ["inkilap", "İnsan Eserleriyle Yaşar", "Atatürk’ün Ölümü ve Sonrası"],
  "İTA.8.7.3.": ["inkilap", "Yeniden Sarsılan Dünya", "Atatürk’ün Ölümü ve Sonrası"],
  "İTA.8.7.4.": ["inkilap", "II. Dünya Savaşı’nın Türkiye’ye Etkileri", "Atatürk’ün Ölümü ve Sonrası"],
  "İTA.8.7.5.": ["inkilap", "Demokrasi Yolunda Güçlü Adımlar", "Atatürk’ün Ölümü ve Sonrası"],
  "M.8.1.1.1.": ["matematik", "Çarpanlar ve Katlar", "Sayılar ve İşlemler"],
  "M.8.1.1.2.": ["matematik", "Çarpanlar ve Katlar", "Sayılar ve İşlemler"],
  "M.8.1.1.3.": ["matematik", "Çarpanlar ve Katlar", "Sayılar ve İşlemler"],
  "M.8.1.2.1.": ["matematik", "Üslü İfadeler", "Sayılar ve İşlemler"],
  "M.8.1.2.2.": ["matematik", "Üslü İfadeler", "Sayılar ve İşlemler"],
  "M.8.1.2.3.": ["matematik", "Üslü İfadeler", "Sayılar ve İşlemler"],
  "M.8.1.2.4.": ["matematik", "Üslü İfadeler", "Sayılar ve İşlemler"],
  "M.8.1.2.5.": ["matematik", "Üslü İfadeler", "Sayılar ve İşlemler"],
  "M.8.1.3.1.": ["matematik", "Kareköklü İfadeler", "Sayılar ve İşlemler"],
  "M.8.1.3.2.": ["matematik", "Kareköklü İfadeler", "Sayılar ve İşlemler"],
  "M.8.1.3.3.": ["matematik", "Kareköklü İfadeler", "Sayılar ve İşlemler"],
  "M.8.1.3.4.": ["matematik", "Kareköklü İfadeler", "Sayılar ve İşlemler"],
  "M.8.1.3.5.": ["matematik", "Kareköklü İfadeler", "Sayılar ve İşlemler"],
  "M.8.1.3.6.": ["matematik", "Kareköklü İfadeler", "Sayılar ve İşlemler"],
  "M.8.1.3.7.": ["matematik", "Kareköklü İfadeler", "Sayılar ve İşlemler"],
  "M.8.1.3.8.": ["matematik", "Kareköklü İfadeler", "Sayılar ve İşlemler"],
  "M.8.2.1.1.": ["matematik", "Cebirsel İfadeler ve Özdeşlikler", "Cebir"],
  "M.8.2.1.2.": ["matematik", "Cebirsel İfadeler ve Özdeşlikler", "Cebir"],
  "M.8.2.1.3.": ["matematik", "Cebirsel İfadeler ve Özdeşlikler", "Cebir"],
  "M.8.2.1.4.": ["matematik", "Cebirsel İfadeler ve Özdeşlikler", "Cebir"],
  "M.8.2.2.1.": ["matematik", "Doğrusal Denklemler", "Cebir"],
  "M.8.2.2.2.": ["matematik", "Doğrusal Denklemler", "Cebir"],
  "M.8.2.2.3.": ["matematik", "Doğrusal Denklemler", "Cebir"],
  "M.8.2.2.4.": ["matematik", "Doğrusal Denklemler", "Cebir"],
  "M.8.2.2.5.": ["matematik", "Doğrusal Denklemler", "Cebir"],
  "M.8.2.2.6.": ["matematik", "Doğrusal Denklemler", "Cebir"],
  "M.8.2.3.1.": ["matematik", "Eşitsizlikler", "Cebir"],
  "M.8.2.3.2.": ["matematik", "Eşitsizlikler", "Cebir"],
  "M.8.2.3.3.": ["matematik", "Eşitsizlikler", "Cebir"],
  "M.8.3.1.1.": ["matematik", "Üçgenler", "Geometri ve Ölçme"],
  "M.8.3.1.2.": ["matematik", "Üçgenler", "Geometri ve Ölçme"],
  "M.8.3.1.3.": ["matematik", "Üçgenler", "Geometri ve Ölçme"],
  "M.8.3.1.4.": ["matematik", "Üçgenler", "Geometri ve Ölçme"],
  "M.8.3.1.5.": ["matematik", "Üçgenler", "Geometri ve Ölçme"],
  "M.8.3.2.1.": ["matematik", "Dönüşüm Geometrisi", "Geometri ve Ölçme"],
  "M.8.3.2.2.": ["matematik", "Dönüşüm Geometrisi", "Geometri ve Ölçme"],
  "M.8.3.2.3.": ["matematik", "Dönüşüm Geometrisi", "Geometri ve Ölçme"],
  "M.8.3.3.1.": ["matematik", "Eşlik ve Benzerlik", "Geometri ve Ölçme"],
  "M.8.3.3.2.": ["matematik", "Eşlik ve Benzerlik", "Geometri ve Ölçme"],
  "M.8.3.4.1.": ["matematik", "Geometrik Cisimler", "Geometri ve Ölçme"],
  "M.8.3.4.2.": ["matematik", "Geometrik Cisimler", "Geometri ve Ölçme"],
  "M.8.3.4.3.": ["matematik", "Geometrik Cisimler", "Geometri ve Ölçme"],
  "M.8.3.4.4.": ["matematik", "Geometrik Cisimler", "Geometri ve Ölçme"],
  "M.8.3.4.5.": ["matematik", "Geometrik Cisimler", "Geometri ve Ölçme"],
  "M.8.3.4.6.": ["matematik", "Geometrik Cisimler", "Geometri ve Ölçme"],
  "M.8.4.1.1.": ["matematik", "Veri Analizi", "Veri İşleme"],
  "M.8.4.1.2.": ["matematik", "Veri Analizi", "Veri İşleme"],
  "M.8.5.1.1.": ["matematik", "Basit Olayların Olma Olasılığı", "Olasılık"],
  "M.8.5.1.2.": ["matematik", "Basit Olayların Olma Olasılığı", "Olasılık"],
  "M.8.5.1.3.": ["matematik", "Basit Olayların Olma Olasılığı", "Olasılık"],
  "M.8.5.1.4.": ["matematik", "Basit Olayların Olma Olasılığı", "Olasılık"],
  "M.8.5.1.5.": ["matematik", "Basit Olayların Olma Olasılığı", "Olasılık"],
  "T.8.4.9.": ["turkce", "Paragrafta Anlam", "Yazma"],
  "T.8.4.8.": ["turkce", "Paragrafta Anlam", "Yazma"],
  "T.8.4.7.": ["turkce", "Atasözü-Deyim-Özdeyiş", "Yazma"],
  "T.8.4.6.": ["turkce", "Paragrafta Anlam", "Yazma"],
  "T.8.4.5.": ["turkce", "Paragrafta Anlam", "Yazma"],
  "T.8.4.4.2.": ["turkce", "Paragrafta Anlam", "Yazma"],
  "T.8.4.4.1.": ["turkce", "Paragrafta Anlam", "Yazma"],
  "T.8.4.3.2.": ["turkce", "Paragrafta Anlam", "Yazma"],
  "T.8.4.3.1.": ["turkce", "Paragrafta Anlam", "Yazma"],
  "T.8.4.20.3.": ["turkce", "Fiilde Çatı", "Yazma"],
  "T.8.4.20.2.": ["turkce", "Fiilde Çatı", "Yazma"],
  "T.8.4.20.1.": ["turkce", "Fiilde Çatı", "Yazma"],
  "T.8.4.2.2.": ["turkce", "Paragrafta Anlam", "Yazma"],
  "T.8.4.2.1.": ["turkce", "Paragrafta Anlam", "Yazma"],
  "T.8.4.19.9.": ["turkce", "Cümle Türleri", "Yazma"],
  "T.8.4.19.8.": ["turkce", "Cümle Türleri", "Yazma"],
  "T.8.4.19.7.": ["turkce", "Cümle Türleri", "Yazma"],
  "T.8.4.19.6.": ["turkce", "Cümle Türleri", "Yazma"],
  "T.8.4.19.5.": ["turkce", "Cümle Türleri", "Yazma"],
  "T.8.4.19.4.": ["turkce", "Cümle Türleri", "Yazma"],
  "T.8.4.19.3.": ["turkce", "Cümle Türleri", "Yazma"],
  "T.8.4.19.2.": ["turkce", "Cümle Türleri", "Yazma"],
  "T.8.4.19.1.": ["turkce", "Cümle Türleri", "Yazma"],
  "T.8.4.18.6.": ["turkce", "Cümlenin Ögeleri", "Yazma"],
  "T.8.4.18.5.": ["turkce", "Cümlenin Ögeleri", "Yazma"],
  "T.8.4.18.4.": ["turkce", "Cümlenin Ögeleri", "Yazma"],
  "T.8.4.18.3.": ["turkce", "Cümlenin Ögeleri", "Yazma"],
  "T.8.4.18.2.": ["turkce", "Cümlenin Ögeleri", "Yazma"],
  "T.8.4.18.1.": ["turkce", "Cümlenin Ögeleri", "Yazma"],
  "T.8.4.16.9.": ["turkce", "Yazım Kuralları", "Yazma"],
  "T.8.4.16.8.": ["turkce", "Yazım Kuralları", "Yazma"],
  "T.8.4.16.7.": ["turkce", "Yazım Kuralları", "Yazma"],
  "T.8.4.16.6.": ["turkce", "Noktalama İşaretleri", "Yazma"],
  "T.8.4.16.5.": ["turkce", "Noktalama İşaretleri", "Yazma"],
  "T.8.4.16.4.": ["turkce", "Noktalama İşaretleri", "Yazma"],
  "T.8.4.16.3.": ["turkce", "Noktalama İşaretleri", "Yazma"],
  "T.8.4.16.20.": ["turkce", "Yazım Kuralları", "Yazma"],
  "T.8.4.16.2.": ["turkce", "Noktalama İşaretleri", "Yazma"],
  "T.8.4.16.19.": ["turkce", "Yazım Kuralları", "Yazma"],
  "T.8.4.16.18.": ["turkce", "Yazım Kuralları", "Yazma"],
  "T.8.4.16.17.": ["turkce", "Yazım Kuralları", "Yazma"],
  "T.8.4.16.16.": ["turkce", "Yazım Kuralları", "Yazma"],
  "T.8.4.16.15.": ["turkce", "Yazım Kuralları", "Yazma"],
  "T.8.4.16.14.": ["turkce", "Yazım Kuralları", "Yazma"],
  "T.8.4.16.13.": ["turkce", "Yazım Kuralları", "Yazma"],
  "T.8.4.16.12.": ["turkce", "Yazım Kuralları", "Yazma"],
  "T.8.4.16.11.": ["turkce", "Yazım Kuralları", "Yazma"],
  "T.8.4.16.10.": ["turkce", "Yazım Kuralları", "Yazma"],
  "T.8.4.16.1.": ["turkce", "Noktalama İşaretleri", "Yazma"],
  "T.8.4.15.": ["turkce", "Geçiş ve Bağlantı İfadeleri", "Yazma"],
  "T.8.4.14.2.": ["turkce", "Paragrafta Anlam", "Yazma"],
  "T.8.4.14.1.": ["turkce", "Paragrafta Anlam", "Yazma"],
  "T.8.4.13.": ["turkce", "Paragrafta Anlam", "Yazma"],
  "T.8.4.12.": ["turkce", "Paragrafta Anlam", "Yazma"],
  "T.8.4.11.": ["turkce", "Paragrafta Anlam", "Yazma"],
  "T.8.4.10.": ["turkce", "Dilimize Yerleşmemiş Yabancı Kelimeler", "Yazma"],
  "T.8.4.1.": ["turkce", "Paragrafta Anlam", "Yazma"],
  "T.8.3.9.4.": ["turkce", "Fiilimsi", "Okuma"],
  "T.8.3.9.3.": ["turkce", "Fiilimsi", "Okuma"],
  "T.8.3.9.2.": ["turkce", "Fiilimsi", "Okuma"],
  "T.8.3.9.1.": ["turkce", "Fiilimsi", "Okuma"],
  "T.8.3.8.6.": ["turkce", "Anlatım Bozukluğu", "Okuma"],
  "T.8.3.8.5.": ["turkce", "Anlatım Bozukluğu", "Okuma"],
  "T.8.3.8.4.": ["turkce", "Anlatım Bozukluğu", "Okuma"],
  "T.8.3.8.3.": ["turkce", "Anlatım Bozukluğu", "Okuma"],
  "T.8.3.8.2.": ["turkce", "Anlatım Bozukluğu", "Okuma"],
  "T.8.3.8.1.": ["turkce", "Anlatım Bozukluğu", "Okuma"],
  "T.8.3.7.6.": ["turkce", "Söz Sanatları", "Okuma"],
  "T.8.3.7.5.": ["turkce", "Söz Sanatları", "Okuma"],
  "T.8.3.7.4.": ["turkce", "Söz Sanatları", "Okuma"],
  "T.8.3.7.3.": ["turkce", "Söz Sanatları", "Okuma"],
  "T.8.3.7.2.": ["turkce", "Söz Sanatları", "Okuma"],
  "T.8.3.7.1.": ["turkce", "Söz Sanatları", "Okuma"],
  "T.8.3.6.3.": ["turkce", "Özdeyişler", "Okuma"],
  "T.8.3.6.2.": ["turkce", "Deyim", "Okuma"],
  "T.8.3.6.1.": ["turkce", "Atasözü", "Okuma"],
  "T.8.3.5.9.": ["turkce", "Sözcükte Anlam", "Okuma"],
  "T.8.3.5.8.": ["turkce", "Sözcükte Anlam", "Okuma"],
  "T.8.3.5.7.": ["turkce", "Sözcükte Anlam", "Okuma"],
  "T.8.3.5.6.": ["turkce", "Sözcükte Anlam", "Okuma"],
  "T.8.3.5.5.": ["turkce", "Sözcükte Anlam", "Okuma"],
  "T.8.3.5.4.": ["turkce", "Sözcükte Anlam", "Okuma"],
  "T.8.3.5.3.": ["turkce", "Sözcükte Anlam", "Okuma"],
  "T.8.3.5.2.": ["turkce", "Sözcükte Anlam", "Okuma"],
  "T.8.3.5.15.": ["turkce", "Sözcükte Anlam", "Okuma"],
  "T.8.3.5.14.": ["turkce", "Sözcükte Anlam", "Okuma"],
  "T.8.3.5.13.": ["turkce", "Sözcükte Anlam", "Okuma"],
  "T.8.3.5.12.": ["turkce", "Sözcükte Anlam", "Okuma"],
  "T.8.3.5.11.": ["turkce", "Sözcükte Anlam", "Okuma"],
  "T.8.3.5.10.": ["turkce", "Sözcükte Anlam", "Okuma"],
  "T.8.3.5.1.": ["turkce", "Sözcükte Anlam", "Okuma"],
  "T.8.3.35.2.": ["turkce", "Paragrafta Anlam", "Yazma"],
  "T.8.3.35.1.": ["turkce", "Paragrafta Anlam", "Yazma"],
  "T.8.3.34.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.33.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.32.": ["turkce", "Tablo ve Grafik Okuma", "Okuma"],
  "T.8.3.31.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.30.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.29.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.28.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.27.": ["turkce", "Görseli Yorumlama", "Okuma"],
  "T.8.3.26.": ["turkce", "Paragrafta Anlam-Metin Türleri", "Okuma"],
  "T.8.3.25.9.": ["turkce", "Cümlede Anlam", "Okuma"],
  "T.8.3.25.8.": ["turkce", "Cümlede Anlam", "Okuma"],
  "T.8.3.25.7.": ["turkce", "Cümlede Anlam", "Okuma"],
  "T.8.3.25.6.": ["turkce", "Cümlede Anlam", "Okuma"],
  "T.8.3.25.4.": ["turkce", "Cümlede Anlam", "Okuma"],
  "T.8.3.25.3.": ["turkce", "Cümlede Anlam", "Okuma"],
  "T.8.3.25.2.": ["turkce", "Cümlede Anlam", "Okuma"],
  "T.8.3.25.17.": ["turkce", "Cümlede Anlam", "Okuma"],
  "T.8.3.25.16.": ["turkce", "Cümlede Anlam", "Okuma"],
  "T.8.3.25.15.": ["turkce", "Cümlede Anlam", "Okuma"],
  "T.8.3.25.14.": ["turkce", "Cümlede Anlam", "Okuma"],
  "T.8.3.25.13.": ["turkce", "Cümlede Anlam", "Okuma"],
  "T.8.3.25.12.": ["turkce", "Cümlede Anlam", "Okuma"],
  "T.8.3.25.11.": ["turkce", "Cümlede Anlam", "Okuma"],
  "T.8.3.25.10.": ["turkce", "Cümlede Anlam", "Okuma"],
  "T.8.3.25.1.": ["turkce", "Cümlede Anlam", "Okuma"],
  "T.8.3.25.": ["turkce", "Cümlede Anlam", "Okuma"],
  "T.8.3.24.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.23.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.22.2.": ["turkce", "Sözel Mantık ve Muhakeme", "Okuma"],
  "T.8.3.22.1.": ["turkce", "Sözel Mantık ve Muhakeme", "Okuma"],
  "T.8.3.21.5.": ["turkce", "Cümlede Anlam", "Okuma"],
  "T.8.3.21.4.": ["turkce", "Cümlede Anlam", "Okuma"],
  "T.8.3.21.3.": ["turkce", "Cümlede Anlam", "Okuma"],
  "T.8.3.21.2.": ["turkce", "Cümlede Anlam", "Okuma"],
  "T.8.3.21.1.": ["turkce", "Cümlede Anlam", "Okuma"],
  "T.8.3.20.3.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.20.2.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.20.1.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.19.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.18.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.17.2.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.17.1.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.16.5.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.16.4.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.16.3.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.16.2.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.16.1.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.15.1.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.14.2.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.14.1.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.13.3.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.12.1.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.11.1.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.10.6.": ["turkce", "Geçiş ve Bağlantı İfadeleri", "Okuma"],
  "T.8.3.10.5.": ["turkce", "Geçiş ve Bağlantı İfadeleri", "Okuma"],
  "T.8.3.10.4.": ["turkce", "Geçiş ve Bağlantı İfadeleri", "Okuma"],
  "T.8.3.10.3.": ["turkce", "Geçiş ve Bağlantı İfadeleri", "Okuma"],
  "T.8.3.10.2.": ["turkce", "Geçiş ve Bağlantı İfadeleri", "Okuma"],
  "T.8.3.10.1.": ["turkce", "Geçiş ve Bağlantı İfadeleri", "Okuma"],
  "F.8.1.1.": ["fen", "Mevsimlerin Oluşumu", "Mevsimler ve İklim"],
  "F.8.1.2.": ["fen", "İklim ve Hava Hareketleri", "Mevsimler ve İklim"],
  "F.8.2.1.": ["fen", "DNA ve Genetik Kod", "DNA ve Genetik Kod"],
  "F.8.2.2.": ["fen", "Kalıtım", "DNA ve Genetik Kod"],
  "F.8.2.3.": ["fen", "Mutasyon ve Modifikasyon", "DNA ve Genetik Kod"],
  "F.8.2.4.": ["fen", "Adaptasyon (Çevreye Uyum)", "DNA ve Genetik Kod"],
  "F.8.2.5.": ["fen", "Biyoteknoloji", "DNA ve Genetik Kod"],
  "F.8.3.1.": ["fen", "Basınç", "Basınç"],
  "F.8.4.1.": ["fen", "Periyodik Sistem", "Madde ve Endüstri"],
  "F.8.4.2.": ["fen", "Fiziksel ve Kimyasal Değişimler", "Madde ve Endüstri"],
  "F.8.4.3.": ["fen", "Kimyasal Tepkimeler", "Madde ve Endüstri"],
  "F.8.4.4.": ["fen", "Asitler ve Bazlar", "Madde ve Endüstri"],
  "F.8.4.5.": ["fen", "Maddenin Isı ile Etkileşimi", "Madde ve Endüstri"],
  "F.8.4.6.": ["fen", "Türkiye'de Kimya Endüstrisi", "Madde ve Endüstri"],
  "F.8.5.1.": ["fen", "Basit Makineler", "Basit Makineler"],
  "F.8.6.1.": ["fen", "Besin Zinciri ve Enerji Akışı", "Enerji Dönüşümleri ve Çevre Bilimi"],
  "F.8.6.2.": ["fen", "Enerji Dönüşümleri", "Enerji Dönüşümleri ve Çevre Bilimi"],
  "F.8.6.3.": ["fen", "Madde Döngüleri ve Çevre Sorunları", "Enerji Dönüşümleri ve Çevre Bilimi"],
  "F.8.6.4.": ["fen", "Sürdürülebilir Kalkınma", "Enerji Dönüşümleri ve Çevre Bilimi"],
  "F.8.7.1.": ["fen", "Elektrik Yükleri ve Elektriklenme", "Elektrik Yükleri ve Elektrik Enerjisi"],
  "F.8.7.2.": ["fen", "Elektrik Yüklü Cisimler", "Elektrik Yükleri ve Elektrik Enerjisi"],
  "F.8.7.3.": ["fen", "Elektrik Enerjisinin Dönüşümü", "Elektrik Yükleri ve Elektrik Enerjisi"],
  "M.8.1.1.": ["matematik", "Çarpanlar ve Katlar", "Sayılar ve İşlemler"],
  "M.8.1.2.": ["matematik", "Üslü İfadeler", "Sayılar ve İşlemler"],
  "M.8.1.3.": ["matematik", "Kareköklü İfadeler", "Sayılar ve İşlemler"],
  "M.8.2.1.": ["matematik", "Cebirsel İfadeler ve Özdeşlikler", "Cebir"],
  "M.8.2.2.": ["matematik", "Doğrusal Denklemler", "Cebir"],
  "M.8.2.3.": ["matematik", "Eşitsizlikler", "Cebir"],
  "M.8.3.1.": ["matematik", "Üçgenler", "Geometri ve Ölçme"],
  "M.8.3.2.": ["matematik", "Dönüşüm Geometrisi", "Geometri ve Ölçme"],
  "M.8.3.3.": ["matematik", "Eşlik ve Benzerlik", "Geometri ve Ölçme"],
  "M.8.3.4.": ["matematik", "Geometrik Cisimler", "Geometri ve Ölçme"],
  "M.8.4.1.": ["matematik", "Veri Analizi", "Veri İşleme"],
  "M.8.5.1.": ["matematik", "Basit Olayların Olma Olasılığı", "Olasılık"],
  "T.8.4.4.": ["turkce", "Paragrafta Anlam", "Yazma"],
  "T.8.4.3.": ["turkce", "Paragrafta Anlam", "Yazma"],
  "T.8.4.20.": ["turkce", "Fiilde Çatı", "Yazma"],
  "T.8.4.2.": ["turkce", "Paragrafta Anlam", "Yazma"],
  "T.8.4.19.": ["turkce", "Cümle Türleri", "Yazma"],
  "T.8.4.18.": ["turkce", "Cümlenin Ögeleri", "Yazma"],
  "T.8.4.14.": ["turkce", "Paragrafta Anlam", "Yazma"],
  "T.8.3.9.": ["turkce", "Fiilimsi", "Okuma"],
  "T.8.3.8.": ["turkce", "Anlatım Bozukluğu", "Okuma"],
  "T.8.3.7.": ["turkce", "Söz Sanatları", "Okuma"],
  "T.8.3.5.": ["turkce", "Sözcükte Anlam", "Okuma"],
  "T.8.3.35.": ["turkce", "Paragrafta Anlam", "Yazma"],
  "T.8.3.22.": ["turkce", "Sözel Mantık ve Muhakeme", "Okuma"],
  "T.8.3.21.": ["turkce", "Cümlede Anlam", "Okuma"],
  "T.8.3.20.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.17.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.16.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.15.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.14.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.13.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.12.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.11.": ["turkce", "Paragrafta Anlam", "Okuma"],
  "T.8.3.10.": ["turkce", "Geçiş ve Bağlantı İfadeleri", "Okuma"],
};
