import { StyleSheet } from '@react-pdf/renderer';

export const colors = {
  border: '#cbd5e1',
  headerBg: '#eef2ff',
  headerText: '#1e293b',
  text: '#0f172a',
  muted: '#64748b',
  rowAlt: '#f8fafc',
  subjectRow: '#f1f5f9',
  accent: '#4f46e5',
};

export const baseStyles = StyleSheet.create({
  page: {
    fontFamily: 'NotoSans',
    fontSize: 7,
    color: colors.text,
    paddingTop: 24,
    paddingBottom: 32,
    paddingHorizontal: 24,
  },
  pageLandscape: {
    fontFamily: 'NotoSans',
    fontSize: 6,
    color: colors.text,
    paddingTop: 20,
    paddingBottom: 28,
    paddingHorizontal: 16,
  },
  schoolTitle: {
    fontFamily: 'NotoSans',
    fontSize: 11,
    fontWeight: 700,
    textAlign: 'center',
    marginBottom: 8,
    lineHeight: 1.35,
    paddingHorizontal: 8,
  },
  reportTitle: {
    fontFamily: 'NotoSans',
    fontSize: 9,
    fontWeight: 700,
    textAlign: 'center',
    marginBottom: 6,
    lineHeight: 1.4,
    paddingHorizontal: 10,
  },
  sectionTitle: {
    fontSize: 8,
    fontWeight: 700,
    marginTop: 10,
    marginBottom: 5,
    color: colors.headerText,
  },
  metaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 6,
    fontSize: 7,
  },
  metaItem: {
    flexDirection: 'row',
    gap: 4,
  },
  metaLabel: {
    fontWeight: 700,
  },
  footer: {
    position: 'absolute',
    bottom: 12,
    left: 24,
    right: 24,
    flexDirection: 'row',
    justifyContent: 'space-between',
    fontSize: 6,
    color: colors.muted,
  },
  table: {
    width: '100%',
    borderWidth: 0.5,
    borderColor: colors.border,
    marginTop: 4,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 0.5,
    borderBottomColor: colors.border,
    minHeight: 12,
    alignItems: 'center',
  },
  tableHeaderRow: {
    flexDirection: 'row',
    backgroundColor: colors.headerBg,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.border,
    minHeight: 18,
    alignItems: 'center',
  },
  cellHeader: {
    fontFamily: 'NotoSans',
    paddingVertical: 3,
    paddingHorizontal: 2,
    borderRightWidth: 0.5,
    borderRightColor: colors.border,
    fontSize: 5,
    fontWeight: 700,
    textAlign: 'center',
    lineHeight: 1.25,
  },
  cell: {
    fontFamily: 'NotoSans',
    paddingVertical: 2,
    paddingHorizontal: 2,
    borderRightWidth: 0.5,
    borderRightColor: colors.border,
    fontSize: 6,
    lineHeight: 1.25,
  },
  cellRight: {
    textAlign: 'right',
  },
  cellCenter: {
    textAlign: 'center',
  },
  subjectBanner: {
    fontSize: 8,
    fontWeight: 700,
    marginTop: 6,
    marginBottom: 4,
    textAlign: 'center',
  },
  examListRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 6,
    fontSize: 6,
  },
  examListItem: {
    width: '31%',
  },
});
